name: Frontend CI

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/709426595530/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'github@deep-mark-340004.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'counter'
        runtime: 'python39'
