name: Backend CI/CD

on:
    push:
        branches: [ main ]
        paths:
        - 'backend/**'
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auth
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/143403552712/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'github@pds-cloud-resume.iam.gserviceaccount.com'

    - name: Install Python Dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: "backend/requirements.txt"

    - name: Test with PyTest
      run: python3 -m pytest -s -vvv

    - name: Deploy
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'counter'
        runtime: 'python39'
        region: 'us-west1'
        entry_point: 'visitcount'
        source_dir: 'backend/counter'
